spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm99697
    password: 111294
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    supported-submit-methods: [ "get", "put", "post", "delete", "options", "head", "patch", "trace" ]

  api-docs:
    enabled: true